######################################################################
# Automatically generated by qmake (3.0) Wed Jan 4 14:44:00 2017
######################################################################

TEMPLATE = app
TARGET = Fake_FG
INCLUDEPATH += .
CONFIG += warn_on console thread

macx {
        QMAKE_MAC_SDK = macosx10.12
        CONFIG -= app_bundle
}

# Input
HEADERS += GlowBalls.h SpikeGLHandlerThread.h
SOURCES += Fake_FG_SpikeGL.cpp SpikeGLHandlerThread.cpp ../../PagedRingBuffer.cpp
